baseURL = 'https://danct12.github.io/'
languageCode = 'en-us'
title = "danct12's webpage"

theme = 'amstrad'

[menu]

  [[menu.main]]
    identifier = "posts"
    name = 'Posts'
    url = '/posts/'
    weight = 10

  [[menu.main]]
    identifier = "hardwares"
    name = "Hardwares"
    url = "/hardwares/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 40

[params]
  author = "Danct12"
  copyright = "Content on this site is licensed under CC-BY-SA 4.0 unless otherwise noted."
  defaultimage = "default.jpg"
