baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[params]
  author = "Author"
  copyright = "All rights reserved."
  defaultimage = "default.jpg"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup.goldmark.extensions.typographer]
  disable = true

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
